# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SEC_DEBUG_TSP_LOG) += sec_tsp_log.o
obj-$(CONFIG_INPUT_TOUCHSCREEN_TCLMV2)	+= sec_tclm_v2.o
obj-$(CONFIG_INPUT_SEC_SECURE_TOUCH)	+= sec_secure_touch.o
obj-$(CONFIG_TOUCHSCREEN_DUMP_MODE)	+= sec_tsp_dumpkey.o
obj-$(CONFIG_INPUT_SEC_INPUT) += sec_cmd.o

obj-$(CONFIG_TOUCHSCREEN_SLSI_Y79A)	+= slsi/
