#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/techpack/display/msm -I$(srctree)/techpack/display/msm/dsi -I$(srctree)/techpack/display/msm/sde -I$(srctree)/techpack/display/msm/samsung

obj-y  += ss_dsi_panel_S6E3FA7_AMB628TR01.o
obj-y  += ss_dsi_smart_dimming_S6E3FA7_AMB628TR01.o
obj-y  += ss_dsi_interpolation_S6E3FA7_AMB628TR01.o
