#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_88XXAU)		+= rtl8812au/
obj-$(CONFIG_RTL8188EU)         += rtl8188eus/
obj-$(CONFIG_RTL8822BU)         += rtl88x2bu/

