#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/techpack/display/msm -I$(srctree)/techpack/display/msm/dsi -I$(srctree)/techpack/display/msm/sde -I$(srctree)/techpack/display/msm/samsung

obj-y  += ss_dsi_panel_NT36523_PPA957DB1.o
obj-y  += isl98608_hw_i2c.o
