#
# Self Display Object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/techpack/display/msm -I$(srctree)/techpack/display/msm/dsi -I$(srctree)/techpack/display/msm/sde -I$(srctree)/techpack/display/msm/samsung

obj-y += self_display_FA7.o
obj-y += self_display_FA9.o
obj-y += self_display_HA8.o
obj-y += self_display_HA9.o
obj-y += self_display_HAB.o
obj-y += self_display_XA0.o
obj-y += self_display_6W3.o
obj-y += self_display_HAC.o
obj-y += self_display_XA1.o
obj-y += self_display_UM1.o
