#
# Makefile for STM32 POGO keyboard drivers
#

obj-$(CONFIG_KEYBOARD_STM32_POGO)   += stm32_pogo_i2c.o stm32_pogo_fw.o stm32_pogo_keyboard.o stm32_pogo_touchpad.o ../../hall_ic_logical.o
ccflags-y += -Wformat
